config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  post 'check_orders_money', to: 'dashboard#check_orders_money'
  post 'check_trade_top', to: 'dashboard#check_trade_top'
  post 'check_expense_ratio', to: 'dashboard#check_expense_ratio'
  post 'check_purchase_supplier', to: 'dashboard#check_purchase_supplier'
  post 'check_sale_customer', to: 'dashboard#check_sale_customer'
  post 'intro_clear', to: 'dashboard#intro_clear'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :settings, only: [:index, :update]
  resources :outputs do
    collection do
      post :delete_list
    end
  end
  resources :introjs, only: [:create, :destroy] do
    collection do
      post :find_attribute
    end
  end
  resources :comments, only: [:index, :create, :destroy] do
    get :take_top, on: :member
  end
  resources :users do
    member do
      get :lock
      get :reset
    end
  end
  resources :employee
  resources :roles
  resources :purchase_suppliers do
    collection do
      get :check_purchase_supplier
    end
    member do
      get :export
    end
  end
  resources :sale_customers do
    collection do
      get :check_sale_customer
    end
    member do
      get :export
    end
  end
  resources :purchase_orders do
    member do
      get :pass_check
    end
  end
  resources :sale_orders do
    member do
      get :pass_check
    end
  end
  resources :materials do
    collection do
      get :check_material_name
      get :check_material_specification
    end
  end
  resources :products do
    collection do
      post :get_options
    end
  end
  resources :repos
  resources :proceeds do
    member do
      get :pass_check
    end
  end
  resources :expenses do
    member do
      get :pass_check
      get :pass_reimburse
    end
    collection do
      get :get_expense_type
    end
  end
  resources :change_machines do
    member do
      get :pass_settle
    end
  end
  resources :password_resets, :only => [:edit, :update]


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    # 未审核的内容
    @not_pass_purchase_orders = PurchaseOrder.where(check_status: false, is_invalid: false)
    @not_pass_sale_orders = SaleOrder.where(check_status: false, is_invalid: false)
    @not_pass_proceeds = Proceed.where(check_status: false, is_invalid: false)
    @not_pass_expenses = Expense.where(check_status: false, is_invalid: false)
    @need_reimburses = Expense.where(is_invalid: false, need_reimburse: true)
    @need_pass_settle = ChangeMachine.where(is_settle: false)
    # 最近一星期的单子数
    @last_week_purchase_orders = PurchaseOrder.where(is_invalid: false).where("bill_time > ?", Time.current.midnight - 7.days)
    @last_week_sale_orders = SaleOrder.where(is_invalid: false).where("bill_time > ?", Time.current.midnight - 7.days)
    @last_week_proceeds = Proceed.where(is_invalid: false).where("bill_time > ?", Time.current.midnight - 7.days)
    @last_week_expenses = Expense.where(is_invalid: false).where("bill_time > ?", Time.current.midnight - 7.days)
  end

  def check_orders_money
    @sale_orders = SaleOrder.check_date(params[:start_date], params[:end_date], :total_price)
    @proceeds = Proceed.check_date(params[:start_date], params[:end_date], :actual_amount)
    @purchase_orders = PurchaseOrder.check_date(params[:start_date], params[:end_date], :total_price)
    @expenses = Expense.check_date(params[:start_date], params[:end_date], :actual_amount)
    @ratio = Array.new
    @ratio << @proceeds.values.sum << @expenses.values.sum
  end

  def check_trade_top
    @top_purchase_orders = PurchaseOrder.check_top_to_hash(params[:start_date], params[:end_date], 'purchase_supplier', 'name')
    @top_sale_orders = SaleOrder.check_top_to_hash(params[:start_date], params[:end_date], 'sale_customer', 'name')
  end

  def check_expense_ratio
    @expenses = Expense.check_ratio(params[:start_date], params[:end_date])
  end

  def check_purchase_supplier
    purchase_supplier = PurchaseSupplier.find(params[:purchase_supplier_id].to_i)
    @purchase_orders = purchase_supplier.check_broken_line(params[:start_date], params[:end_date])
    @expenses = purchase_supplier.check_expenses(params[:start_date], params[:end_date])
  end

  def check_sale_customer
    sale_customer = SaleCustomer.find(params[:sale_customer_id].to_i)
    @sale_orders = sale_customer.check_broken_line(params[:start_date], params[:end_date])
    @proceeds = sale_customer.check_proceed(params[:start_date], params[:end_date])
  end

  # 删除所有该用户的新手引导记录
  def intro_clear
    store_referrer_location
    ActiveRecord::Base.connection.execute("delete from intro_histories where user_id =#{params[:id]} ")
    redirect_back_referrer_for root_url
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_common_content.html.erb
<div class="common_content" id="step3">
  <h5>常用功能</h5>
  <div>
    <% if can? :create, Expense %>
      <div class="btn" id="new_expense">
        <%= link_to "填写新的付款单", new_expense_path %>
      </div>

    <% end %>
    <% if can? :create, Proceed %>
      <div class="btn" id="new_proceed">
        <%= link_to "填写新的收款单", new_proceed_path %>
      </div>
    <% end %>
    <% if can? :create, PurchaseOrder %>
      <div class="btn" id="new_purchase_order">
        <%= link_to "填写新的采购单", new_purchase_order_path %>
      </div>
    <% end %>
    <% if can? :create, SaleOrder %>
      <div class="btn" id="new_sale_order">
        <%= link_to "填写新的销售单", new_sale_order_path %>
      </div>
    <% end %>
    <% if can? :create, ChangeMachine %>
      <div class="btn" id="new_change_machine">
        <%= link_to "记录新的改机信息", new_change_machine_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/_info.html.erb
<div id="accordion">
  <div class="card">
    <div class="card-header">
      <a class="card-link" data-toggle="collapse" href="#collapseOne">
        本系统的由来
      </a>
    </div>
    <div id="collapseOne" class="collapse" data-parent="#accordion">
      <div class="card-body">
        <p>在过去小企业工作中发现了一些问题，使得我萌生了将部分工作流程信息化的想法。</p>
        <p>传统工作流程：终端销售采购人员填写单据，将单据交到专门的记录人员。记录人员分门别类后，记入总账。每月和供应商和客户对账时，将相应的记录筛选出来，在Excel里面制作对账单。</p>
        <p>在上述工作流程中，有各种问题出现：</p>
        <p>1. 记录人员繁忙，不能及时记录单据的情况；</p>
        <p>2. 收来的单据上有疑惑，信息不全而需要再去寻找到原始提交单据的人员详细询问的情况；</p>
        <p>3. 单据在转交的过程中遗失；</p>
        <p>4. 制作对账单过程中出现错误；</p>
        <p>5. 管理人员无法及时了解企业的生产资料调度情况，每次查询还要找专门的记录人员去翻找资料；</p>
        <p>6. 其他意外因素。</p>

        <p>本项目为了解决以上各种问题，实现以下功能：</p>
        <p>1. 数量繁多的记录脱离开个别专门的记录人员，终端人员可以自行输入各种单据，相关审核人员审核后记入系统。</p>
        <p>2. 管理人员能清晰直观的看到企业生产资料的出入情况，及各种所需的数据计算结果。</p>
        <p>3. 一键导出对应供应商/客户的对账单，降低耗费时间和减少制作过程中可能出现的错误。</p>
        <p>4. 以上操作都可以在手机上完成，不必守着一台位于公司内部的电脑上了。</p>

        <p>因为企业对于各种工作流程需要定制化的设计，势必不可能一个系统能匹配所有类型的企业，以上系统基于本人在纺织企业工作的两年经验，完全针对该企业工作内容的需要。</p>

      </div>
    </div>
  </div>
</div>

app/views/dashboard/_last_week_status.html.erb
<div class="last_week_status" id="step4">
  <h5>最近7天的情况</h5>
  <div>
    <% if @last_week_purchase_orders.size > 0 %>
      <div id="accordion">
        <div class="card">
          <div class="card-header">
            <a class="card-link" data-toggle="collapse" href="#collapse_21">
              <p>有<%= @last_week_purchase_orders.size %>张采购单</p>
            </a>
          </div>
          <div id="collapse_21" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <% @last_week_purchase_orders.each do |order| %>
                <p> <%= link_to order.material.name, purchase_order_path(order) %>
                  —<%= link_to order.purchase_supplier.name, purchase_supplier_path(order.purchase_supplier.id) %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% if @last_week_sale_orders.size > 0 %>
      <p>有<%= @last_week_sale_orders.size %>张销售单</p>
      <div id="accordion">
        <div class="card">
          <div class="card-header">
            <a class="card-link" data-toggle="collapse" href="#collapse_22">
              <p>有<%= @last_week_sale_orders.size %>张销售单</p>
            </a>
          </div>
          <div id="collapse_22" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <% @last_week_sale_orders.each do |order| %>
                <p> <%= link_to order.product.name, sale_order_path(order) %>
                  —<%= link_to order.sale_customer.name, sale_customer_path(order.sale_customer.id) %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% if @last_week_proceeds.size > 0 %>
      <p>有<%= @last_week_proceeds.size %>张收款单</p>
      <div id="accordion">
        <div class="card">
          <div class="card-header">
            <a class="card-link" data-toggle="collapse" href="#collapse_23">
              <p>有<%= @last_week_proceeds.size %>张收款单</p>
            </a>
          </div>
          <div id="collapse_23" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <% @last_week_proceeds.each do |order| %>
                <p><%= link_to("#{order.sale_customer.name} - #{order.bill_time.localtime.strftime("%Y-%m-%d")}", proceed_path(order)) %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% if @last_week_expenses.size > 0 %>
      <p>有<%= @last_week_expenses.size %>张付款单</p>
      <div id="accordion">
        <div class="card">
          <div class="card-header">
            <a class="card-link" data-toggle="collapse" href="#collapse_24">
              <p>有<%= @last_week_expenses.size %>张付款单</p>
            </a>
          </div>
          <div id="collapse_24" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <% @last_week_expenses.each do |order| %>
                <p><%= link_to("#{order.counterparty} - #{order.bill_time.localtime.strftime("%Y-%m-%d")}", expense_path(order)) %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/_novice_guide.html.erb
<div class="nav-item dropdown" id="novice_guide">
  <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
    新手引导
  </a>
  <div class="dropdown-menu">
    <% if can? :create, Expense %>
      <a class="dropdown-item" id="expense_tour">新的付款单</a>
    <% end %>
    <% if can? :create, Proceed %>
      <a class="dropdown-item" id="proceed_tour">新的收款单</a>
    <% end %>
    <% if can? :create, PurchaseOrder %>
      <a class="dropdown-item" id="purchase_order_tour">新的采购单</a>
    <% end %>
    <% if can? :create, SaleOrder %>
      <a class="dropdown-item" id="sale_order_tour">新的销售单</a>
    <% end %>
    <% if can? :create, ChangeMachine %>
      <a class="dropdown-item" id="change_machine_tour">新的改机记录</a>
    <% end %>
    <% if can? :update, PurchaseSupplier %>
      <a class="dropdown-item" id="change_purchase_supplier_check_money_time_tour">设置初始对账金额</a>
    <% end %>
    <% if can? :export, PurchaseSupplier %>
      <a class="dropdown-item" id="export_sale_customer_tour">导出对账单</a>
    <% end %>
  </div>
</div>

app/views/dashboard/_operations_can_do.html.erb
<div class="operations_can_do" id="step2">
  <h5>待处理清单</h5>
  <div class="not_pass_content">
    <% if can? :pass_check, Expense %>
      <% if @not_pass_expenses.count > 0 %>
        <p>
          审核付款单<span class="badge badge-warning">
        <%= link_to @not_pass_expenses.count, expenses_path(type: "check_status:false") %> </span>
        </p>
      <% end %>
    <% end %>
    <% if can? :pass_check, Proceed %>
      <% if @not_pass_proceeds.count > 0 %>
        <p>
          审核收款单<span class="badge badge-warning">
        <%= link_to @not_pass_proceeds.count, proceeds_path(type: "check_status:false") %></span>
        </p>
      <% end %>
    <% end %>
    <% if can? :pass_check, SaleOrder %>
      <% if @not_pass_sale_orders.count > 0 %>
        <p>
          审核销售单<span class="badge badge-warning">
        <%= link_to @not_pass_sale_orders.count, sale_orders_path(type: "check_status:false") %></span>
        </p>
      <% end %>
    <% end %>
    <% if can? :pass_check, PurchaseOrder %>
      <% if @not_pass_purchase_orders.count > 0 %>
        <p>
          审核采购单<span class="badge badge-warning">
        <%= link_to @not_pass_purchase_orders.count, purchase_orders_path(type: "check_status:false") %></span>
        </p>
      <% end %>
    <% end %>
    <% if can? :pass_reimburse_expense, Expense %>
      <% if @need_reimburses.count > 0 %>
        <div>
          还有未报销单<span class="badge badge-warning">
        <%= link_to @need_reimburses.count, expenses_path(type: "need_reimburse:true") %></span>
        </div>
      <% end %>
    <% end %>
    <% if can? :pass_settle, ChangeMachine %>
      <% if @need_pass_settle.count > 0 %>
        <div>
          还有未结算的改机费用<span class="badge badge-warning">
        <%= link_to @need_pass_settle.count, change_machines_path(type: "is_settle:false") %></span>
        </div>
      <% end %>
    <% end %>
    <hr>
  </div>
</div>

app/views/dashboard/_role_info.html.erb
<div class="role_info" id="step1">
  <h5>角色栏</h5>
  <div id="accordion">
    <% current_user.roles.each do |role| %>
      <div class="card">
        <div class="card-header">
          <a class="card-link" data-toggle="collapse" href="#collapse_<%= role.id %>">
            <%= role.name %>
          </a>
        </div>
        <div id="collapse_<%= role.id %>" class="collapse" data-parent="#accordion">
          <div class="card-body">
            <%= role.description %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/check_expense_ratio.js.erb
var head = $(".chart-container")
head.empty();


<%unless @expenses.blank? %>
head.append("<canvas id=\"check_expense_ratio_chart\"></canvas>\n")
var ctx = $('#check_expense_ratio_chart');
var myChart = new Chart(ctx, {
    type: "pie",
    data: {
        labels: <%=raw @expenses.keys %>,
        datasets: [
            {
                data: <%= raw @expenses.values %>,
                backgroundColor: ["green", "red", "blue","yellow"]
            }
        ]
    }
});
<%else %>
head.append("<p>该时间段内没有找到符合要求的数据</p>");
<%end %>

app/views/dashboard/check_orders_money.js.erb
var head = $(".chart-container")
head.empty();



<%unless @sale_orders.blank? %>
head.append("<canvas id=\"check_sale_proceed_chart\"></canvas>\n");
var ctx = $('#check_sale_proceed_chart');

var myChart = new Chart(ctx, {
    type: "bar",
    data: {
        labels: <%= raw (@sale_orders.keys+@proceeds.keys).uniq.sort  %>,
        datasets: [
            {
                label: '销售额',
                data: <%= raw @sale_orders.values %>,
                backgroundColor: 'blue',

                borderWidth: 1
            }, {
                label: '收款额',
                data: <%= raw @proceeds.values %>,
                backgroundColor: 'green',

                borderWidth: 1
            },


        ]
    },
    options: {
        showlines: false,
        spanGaps: true,
        fill: false,
        bezierCurve: false,
        datasetFill: false
    }
});
<%else %>
head.append("<p>该时间段内没有找到符合要求的数据</p>");
<%end %>

<%unless @purchase_orders.blank? %>
head.append("<canvas id=\"check_purchase_expense_chart\"></canvas>\n");
var ctx = $('#check_purchase_expense_chart');
var myChart = new Chart(ctx, {
    type: "bar",
    data: {
        labels: <%= raw (@purchase_orders.keys+@expenses.keys).uniq.sort  %>,
        datasets: [
            {
                label: '采购金额',
                data: <%= raw @purchase_orders.values %>,
                backgroundColor: 'yellow',

                borderWidth: 1
            }, {
                label: '付款金额',
                data: <%= raw @expenses.values %>,
                backgroundColor: 'red',

                borderWidth: 1
            },


        ]
    },
    options: {
        showlines: false,
        spanGaps: true,
        fill: false,
        bezierCurve: false,
        datasetFill: false
    }
});
<%end %>

<%unless @ratio ==[0,0] %>
head.append("<canvas id=\"check_proceed_expense_chart\"></canvas>\n");

//付款收款的比值
var ctx = $('#check_proceed_expense_chart');
var myChart = new Chart(ctx, {
    type: "pie",
    data: {
        datasets: [
            {
                data: <%= raw @ratio %>,
                backgroundColor: ["green", "red"]
            }
        ],
        labels: ['收款', '付款']
    }
});
<%end %>

app/views/dashboard/check_purchase_supplier.js.erb
var head = $(".chart-container")
head.empty();


<%unless @purchase_orders.blank? %>
head.append("<canvas id=\"check_purchase_supplier_chart\"></canvas>\n")
var ctx = $('#check_purchase_supplier_chart');
var myChart = new Chart(ctx, {
    type: "line",
    data: {
        labels: <%= raw @purchase_orders.keys  %>,
        datasets: [
            {
                label: '采购金额曲线',
                data: <%= raw @purchase_orders.values %>,
                borderColor: 'black',
                borderWidth: 1,
                fill: false
            }
        ]
    }
});
<%else %>
head.append("<p>该时间段内没有找到符合要求的数据</p>");
<%end %>

<%unless @expenses.blank? %>
head.append("<canvas id=\"check_purchase_supplier_chart2\"></canvas>\n")
var ctx = $('#check_purchase_supplier_chart2');
var myChart = new Chart(ctx, {
    type: "line",
    data: {
        labels: <%= raw @expenses.keys  %>,
        datasets: [
            {
                label: '付款金额曲线',
                data: <%= raw @expenses.values %>,
                borderColor: 'red',
                borderWidth: 1,
                fill: false
            }
        ]
    }
});
<%else %>
head.append("<p>该时间段内没有找到符合要求的数据</p>");
<%end %>

app/views/dashboard/check_sale_customer.js.erb
var head = $(".chart-container")
head.empty();


<%unless @sale_orders.blank? %>
head.append("<canvas id=\"check_sale_customer_chart\"></canvas>\n")
var ctx = $('#check_sale_customer_chart');
var myChart = new Chart(ctx, {
    type: "line",
    data: {
        labels: <%= raw @sale_orders.keys  %>,
        datasets: [
            {
                label: '销售金额曲线',
                data: <%= raw @sale_orders.values %>,
                borderColor: 'blue',
                borderWidth: 1,
                fill: false
            }
        ]
    }
});
<%else %>
head.append("<p>该时间段内没有找到符合要求的数据</p>");
<%end %>
<%unless @proceeds.blank? %>
head.append("<canvas id=\"check_sale_customer_chart2\"></canvas>\n")
var ctx = $('#check_sale_customer_chart2');
var myChart = new Chart(ctx, {
    type: "line",
    data: {
        labels: <%= raw @proceeds.keys  %>,
        datasets: [
            {
                label: '收款金额曲线',
                data: <%= raw @proceeds.values %>,
                borderColor: 'green',
                borderWidth: 1,
                fill: false
            }
        ]

    }
});
<%else %>
head.append("<p>该时间段内没有找到符合要求的数据</p>");
<%end %>

app/views/dashboard/check_sale_proceed.js.erb
var head = $(".chart-container")
head.empty();
head.append("<canvas id=\"check_sale_proceed_chart\"></canvas>\n" +
    "      <canvas id=\"check_purchase_expense_chart\"></canvas>\n" +
    "      <canvas id=\"check_proceed_expense_chart\"></canvas>")

<%unless @sale_orders.blank? %>
var ctx = $('#check_sale_proceed_chart');

var myChart = new Chart(ctx, {
    type: "bar",
    data: {
        labels: <%= raw (@sale_orders.keys+@proceeds.keys).uniq.sort  %>,
        datasets: [
            {
                label: '销售额',
                data: <%= raw @sale_orders.values %>,
                backgroundColor: 'blue',

                borderWidth: 1
            }, {
                label: '收款额',
                data: <%= raw @proceeds.values %>,
                backgroundColor: 'green',

                borderWidth: 1
            },


        ]
    },
    options: {
        showlines: false,
        spanGaps: true,
        fill: false,
        bezierCurve: false,
        datasetFill: false
    }
});
<%end %>

<%unless @purchase_orders.blank? %>
var ctx = $('#check_purchase_expense_chart');
var myChart = new Chart(ctx, {
    type: "bar",
    data: {
        labels: <%= raw (@purchase_orders.keys+@expenses.keys).uniq.sort  %>,
        datasets: [
            {
                label: '采购金额',
                data: <%= raw @purchase_orders.values %>,
                backgroundColor: 'yellow',

                borderWidth: 1
            }, {
                label: '付款金额',
                data: <%= raw @expenses.values %>,
                backgroundColor: 'red',

                borderWidth: 1
            },


        ]
    },
    options: {
        showlines: false,
        spanGaps: true,
        fill: false,
        bezierCurve: false,
        datasetFill: false
    }
});
<%end %>

<%unless @ratio ==[0,0] %>
//付款收款的比值
var ctx = $('#check_proceed_expense_chart');
var myChart = new Chart(ctx, {
    type: "pie",
    data: {
        datasets: [
            {
                data: <%= raw @ratio %>,
                backgroundColor: ["green", "red"]
            }
        ],
        labels: ['收款', '付款']
    }
});
<%end %>

app/views/dashboard/check_trade_top.js.erb
var head = $(".chart-container")
head.empty();


<%unless @top_purchase_orders.blank? %>
head.append("<canvas id=\"check_purchase_supplier_top_chart\"></canvas>\n")
var ctx = $('#check_purchase_supplier_top_chart');
var myChart = new Chart(ctx, {
    type: "bar",
    data: {
        labels: <%= raw @top_purchase_orders.keys[0..9]  %>,
        datasets: [
            {
                label: '采购金额',
                data: <%= raw @top_purchase_orders.values[0..9] %>,
                backgroundColor: 'red',
                borderWidth: 1
            }
        ]
    },
    options: {
        showlines: false,
        spanGaps:
            true,
        fill:
            false,
        bezierCurve:
            false,
        datasetFill:
            false
    }
});
<%else %>
head.append("<p>该时间段内没有找到符合要求的数据</p>");
<%end %>

<%unless @top_sale_orders.blank? %>
head.append("<canvas id=\"check_sale_orders_top_chart\"></canvas>\n")
var ctx = $('#check_sale_orders_top_chart');
var myChart = new Chart(ctx, {
    type: "bar",
    data: {
        labels: <%= raw @top_sale_orders.keys[0..9]  %>,
        datasets: [
            {
                label: '销售金额',
                data: <%= raw @top_sale_orders.values[0..9] %>,
                backgroundColor: 'green',
                borderWidth: 1
            }
        ]
    },
    options: {
        showlines: false,
        spanGaps:
            true,
        fill:
            false,
        bezierCurve:
            false,
        datasetFill:
            false
    }
});
<%else %>
head.append("<p>该时间段内没有找到符合要求的数据</p>");
<%end %>

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'dashboard/role_info' %>
    <%= render 'dashboard/operations_can_do' %>
    <%= render 'dashboard/common_content' %>
    <%= render 'dashboard/last_week_status' %>
    <%= render 'dashboard/novice_guide' %>
  </div>
  <div class="col-md-9">
    <p class="alert-warning"> 有任何意见、建议、问题、需要添加的功能请在底部的建议反馈里提交！</p>
    <div class="graph_query" id="step5">
      <h5>图表查询</h5>
      <div class="row no-gutters">
        <p class="col-12 col-md-4">开始日期：<%= date_field_tag :start_date, (Time.current - 7.days).strftime("%Y-%m-%d") %></p>
        <p class="col-12 col-md-4">结束日期：<%= date_field_tag :end_date, (Time.current + 1.day).strftime("%Y-%m-%d") %></p>
      </div>
      <div class="row no-gutters">
        <%= button_tag "订单收支", id: "check_order_money", class: "btn btn-primary" %>
        <%= button_tag "支出类别", id: "check_expense_ratio", class: "btn btn-primary" %>
        <%= button_tag "最高交易金额的公司", id: "check_trade_top", class: "btn btn-primary" %>
      </div>
      <div class="row no-gutters">
        <%= collection_select(:purchase_supplier, 0, PurchaseSupplier.all, :id, :name) %>
        <%= button_tag "供应商货款", id: "check_purchase_supplier", class: "btn btn-primary" %>
        <%= collection_select(:sale_customer, 0, SaleCustomer.all, :id, :name) %>
        <%= button_tag "客户货款", id: "check_sale_customer", class: "btn btn-primary" %>
      </div>
      <div class="chart-container"></div>

    </div>
  </div>
</div>