config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  post 'check_orders_money', to: 'dashboard#check_orders_money'
  post 'check_trade_top', to: 'dashboard#check_trade_top'
  post 'check_expense_ratio', to: 'dashboard#check_expense_ratio'
  post 'check_purchase_supplier', to: 'dashboard#check_purchase_supplier'
  post 'check_sale_customer', to: 'dashboard#check_sale_customer'
  post 'intro_clear', to: 'dashboard#intro_clear'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :settings, only: [:index, :update]
  resources :outputs do
    collection do
      post :delete_list
    end
  end
  resources :introjs, only: [:create, :destroy] do
    collection do
      post :find_attribute
    end
  end
  resources :comments, only: [:index, :create, :destroy] do
    get :take_top, on: :member
  end
  resources :users do
    member do
      get :lock
      get :reset
    end
  end
  resources :employee
  resources :roles
  resources :purchase_suppliers do
    collection do
      get :check_purchase_supplier
    end
    member do
      get :export
    end
  end
  resources :sale_customers do
    collection do
      get :check_sale_customer
    end
    member do
      get :export
    end
  end
  resources :purchase_orders do
    member do
      get :pass_check
    end
  end
  resources :sale_orders do
    member do
      get :pass_check
    end
  end
  resources :materials do
    collection do
      get :check_material_name
      get :check_material_specification
    end
  end
  resources :products do
    collection do
      post :get_options
    end
  end
  resources :repos
  resources :proceeds do
    member do
      get :pass_check
    end
  end
  resources :expenses do
    member do
      get :pass_check
      get :pass_reimburse
    end
    collection do
      get :get_expense_type
    end
  end
  resources :change_machines do
    member do
      get :pass_settle
    end
  end
  resources :password_resets, :only => [:edit, :update]


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/purchase_supplier.rb
class PurchaseSupplier < ApplicationRecord
  has_many :materials
  has_many :purchase_orders
  has_and_belongs_to_many :expenses
  validates :name, uniqueness: true, presence: true

  # 搜索所有的订单，计算一遍
  def calcu_list
    self.calcu_total_payment_required
    self.calcu_paid
    self.calcu_unpaid
    self.calcu_deposit
  end

  # 从采购单里计算总共需要付款,需要减去退货单的
  def calcu_total_payment_required
    # 得到已经通过审核且未作废的采购单
    purchase_orders = self.purchase_orders.where(check_status: true, is_invalid: false)
    # 存在清算日期和金额的，计算日期之后的账单
    if self.check_money_time && self.check_money
      # 得到清算时间后的订单
      purchase_orders = purchase_orders.where("bill_time > ?", self.check_money_time)
      # 计算应付的钱，非退货单加上设定的清算金额
      need_pay_money = purchase_orders.where(is_return: false).collect(&:total_price).sum + self.check_money
      # 再加包含运费的单子里的运费
      need_pay_money += purchase_orders.where(is_return: false, our_freight: false).where.not(freight: nil).map(&:freight).sum
    else
      # 计算得到所有非退货单的总值
      need_pay_money = purchase_orders.where(is_return: false).collect(&:total_price).sum
      # 再加包含运费的单子里的运费
      need_pay_money += purchase_orders.where(is_return: false, our_freight: false).where.not(freight: nil).map(&:freight).sum
    end
    # 计算得到退货单的总值
    is_return_money = purchase_orders.where(is_return: true).collect(&:total_price).sum
    is_return_money += purchase_orders.where(is_return: true, our_freight: false).where.not(freight: nil).map(&:freight).sum
    # 更新
    self.total_payment_required = need_pay_money - is_return_money
    self.save
  end

  # 从支出单里计算总共已付的款(账面款)
  def calcu_paid
    # 得到已经通过审核且未作废的采购单
    expenses = self.expenses.where(check_status: true, is_invalid: false)
    # 存在清算日期和金额的，计算日期之后的账单
    if self.check_money_time && self.check_money
      # 计算清算日期后的所有付款单的总值
      self.paid = expenses.where("created_at > ?", self.check_money_time).collect(&:paper_amount).sum
    else
      # 计算所有符合要求的付款单总值
      self.paid = expenses.collect(&:paper_amount).sum
    end
    self.save
  end

  # 计算未付的款
  def calcu_unpaid
    if self.total_payment_required && self.paid
      self.update_columns(unpaid: self.total_payment_required - self.paid)
    end
  end

  # 计算所有采购单的押金
  def calcu_deposit
    deposits = self.purchase_orders.where(check_status: true, is_invalid: false)
    # 存在清算日期和金额的，计算日期之后的账单
    if self.check_money_time && self.check_money
      # 得到清算时间后的订单
      deposits = deposits.where("bill_time > ?", self.check_money_time)
    end
    deposits = deposits.where("deposit > 0")
    # 计算得到所有非退货单的总值
    paid_deposit = deposits.where(is_return: false).map(&:deposit).sum
    # 计算退货单上的押金，就是从供应商那里收回的
    collection_deposit = deposits.where(is_return: true).map(&:deposit).sum
    # 总的押金等于付出的押金减去收回的押金，等于零机是回本，小于0就是赚，但这是不可能的
    self.total_deposit = paid_deposit - collection_deposit
    self.save
  end

  # 获取供货商的订单金额数据，做曲线显示
  def check_broken_line(start_date, end_date)
    orders = self.purchase_orders.where(bill_time: start_date..end_date, is_invalid: false, check_status: true)
    h = Hash.new
    orders.select(:bill_time, :total_price).each do |order|
      order_time = order.bill_time.strftime("%Y-%m-%d")
      if h.has_key? order_time
        h[order_time] += order.total_price
      else
        h.store(order_time, order.total_price)
      end
    end
    h
  end

  # 获取供货商的已付金额数据，做曲线显示
  def check_expenses(start_date, end_date)
    expenses = self.expenses.where(bill_time: start_date..end_date, is_invalid: false, check_status: true)
    h = Hash.new
    expenses.select(:bill_time, :paper_amount).each do |expense|
      order_time = expense.bill_time.strftime("%Y-%m-%d")
      if h.has_key? order_time
        h[order_time] += expense.paper_amount
      else
        h.store(expense.bill_time.strftime("%Y-%m-%d"), expense.paper_amount)
      end
    end
    h
  end

end

app/controllers/purchase_suppliers_controller.rb
class PurchaseSuppliersController < ApplicationController
  before_action :get_supplier, only: [:edit, :show, :update, :destroy]
  load_and_authorize_resource

  def index
    if params.has_key?(:search) && params[:search] != ""
      @suppliers = PurchaseSupplier.search_name(params[:search]).order("name").page(params[:page])
    else
      @suppliers = PurchaseSupplier.order("name").page(params[:page])
    end
  end

  def new
    @supplier = PurchaseSupplier.new
  end

  def edit

  end

  def show
    @purchase_orders = @supplier.purchase_orders.where(is_invalid: false).count
    @expenses = @supplier.expenses.where(is_invalid: false).count
  end

  def create
    @supplier = PurchaseSupplier.new(purchase_supplier_params)
    if @supplier.save
      flash[:success] = "创建成功"
      redirect_to purchase_suppliers_path
    else
      flash[:warning] = "#{@supplier.errors.full_messages.join(',')}"
      render "purchase_suppliers/new"
    end
  end

  def update
    if @supplier.update(purchase_supplier_params)
      # 如果更新了清算金额和日期，重新计算总额
      # if @supplier.check_money > 0 && @supplier.check_money_time
      @supplier.calcu_list
      # end
      flash[:success] = "成功更新供应商信息"
      redirect_to purchase_supplier_url(@supplier)
    else
      flash[:warning] = "#{@supplier.errors.full_messages.join(',')}"
      render "purchase_suppliers/edit"
    end
  end

  def destroy
    if @supplier.purchase_orders.where(check_status: true).blank? && @supplier.expenses.blank?
      PurchaseSupplier.delete(@supplier)
      flash[:warning] = "已经删除供应商#{@supplier.name}了"
      redirect_to purchase_suppliers_path
    else
      flash[:warning] = "该供应商名下下还有关联的采购订单/付款单，不能删除"
      redirect_to purchase_suppliers_path
    end
  end

  def check_purchase_supplier
    @purchase_supplier = PurchaseSupplier.search_name(params[:term]).map(&:name)
    render json: @purchase_supplier
  end

  def export
    @purchase_supplier = PurchaseSupplier.find(params[:id])
    if @purchase_supplier.check_money_time
      purchase_orders = PurchaseOrder.includes(:materials)
                            .where(purchase_supplier_id: params[:id], check_status: true, is_invalid: false)
                            .where("bill_time >=?", @purchase_supplier.check_money_time)
      @purchase_orders = purchase_orders.where(is_return: false)
      @purchase_orders_return = purchase_orders.where(is_return: true)
      @expenses = PurchaseSupplier.select("expenses.bill_time,expenses.paper_amount").joins(:expenses)
                      .where(id: params[:id])
                      .where("bill_time >=? and expenses.check_status=?", @purchase_supplier.check_money_time, true)
    else
      purchase_orders = PurchaseOrder.includes(:materials)
                            .where(purchase_supplier_id: params[:id], check_status: true, is_invalid: false)
      @purchase_orders = purchase_orders.where(is_return: false)
      @purchase_orders_return = purchase_orders.where(is_return: true)
      @expenses = PurchaseSupplier.select("expenses.bill_time,expenses.paper_amount")
                      .joins(:expenses)
                      .where(id: params[:id])
                      .where("check_status=?", true)
    end
    @rows_count = @purchase_orders.size + @purchase_orders_return.size + @expenses.size + 1
    respond_to do |format|
      format.html
      # format.csv {send_data @purchase_order.to_csv}
      format.xls #{send_data @purchase_order.to_csv(col_sep: "\t")}
    end
  end

  private

  def get_supplier
    @supplier = PurchaseSupplier.find(params[:id])
  end

  def purchase_supplier_params
    params.require(:purchase_supplier).permit(:name, :contacts, :phone, :address, :description, :status,
                                              :check_money, :check_money_time)
  end

end

app/helpers/purchase_supplier_helper.rb
module PurchaseSupplierHelper
end

app/views/purchase_suppliers/_form_content.html.erb
<div class="form-group">
  <%= f.label :name, "公司名" %>
  <%= f.text_field :name, required: "required", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :contacts, "联系人姓名" %>
  <%= f.text_field :contacts, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :phone, "联系号码" %>
  <%= f.text_field :phone, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :address, "地址" %>
  <%= f.text_field :address, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description, "描述" %>
  <%= f.text_field :description, class: "form-control" %>
</div>
<div class="form-group" id="check_money">
  <%= f.label :check_money, "清算金额" %>
  <a class="far fa-question-circle" data-toggle="tooltip" data-placement="right" title="设定和供应商的初始未付货款,负值代表供应商欠我们钱"> </a>
  <%= f.number_field :check_money, placeholder: "设定初始未付货款", min: 0, step: 0.01, class: "form-control" %>
</div>
<div class="form-group" id="check_money_time">
  <%= f.label :check_money_time, "清算时间" %>
  <a class="far fa-question-circle" data-toggle="tooltip" data-placement="right" title="在此时间前记录的订单和付款单将不会参与总值计算"> </a>
  <%= f.datetime_field :check_money_time, class: "form-control" %>
  <a id="check_money_time_clear">清除清算金额和日期(不需要设置清算日期和金额，点击)</a>
</div>

app/views/purchase_suppliers/_show_content.html.erb
<table class="table">
  <tbody>
  <tr>
    <th>供应商名称</th>
    <td><%= object.name %></td>
  </tr>
  <tr>
    <th>描述</th>
    <td><%= object.description %></td>
  </tr>
  <tr>
    <th>联系人</th>
    <td><%= object.contacts %></td>
  </tr>
  <tr>
    <th>联系电话</th>
    <td><%= object.phone %></td>
  </tr>
  <tr>
    <th>地址</th>
    <td><%= object.address %></td>
  </tr>
  <tr>
    <th>总计货款</th>
    <td><%= object.total_payment_required %></td>
  </tr>
  <tr>
    <th>押金</th>
    <td><%= object.total_deposit %></td>
  </tr>
  <tr>
    <th>已付</th>
    <td><%= object.paid %></td>
  </tr>
  <tr>
    <th>未付</th>
    <td><%= object.unpaid %></td>
  </tr>
  <% if object.check_money %>
    <tr>
      <th>清算金额</th>
      <td><%= object.check_money %></td>
    </tr>
    <tr>
      <th>清算日期</th>
      <td><%= object.check_money_time %></td>
    </tr>
  <% end %>
  <tr>
    <th>已有订单数</th>
    <td><%= link_to @purchase_orders, purchase_orders_path(:search => "#{object.name}") %></td>
  </tr>
  <tr>
    <th>已有付款单数</th>
    <td><%= link_to @expenses, expenses_path(:search => "#{object.name}") %></td>
  </tr>
  </tbody>
</table>

app/views/purchase_suppliers/edit.html.erb
<% provide :button_text, "更新" %>
<% provide :title, "编辑供应商信息" %>
<% provide :method, :patch %>
<% provide :back_url, purchase_supplier_url(@supplier) %>

<%= render 'shard/form', object: @supplier, url: purchase_supplier_path,type:"purchase_supplier",type_2:"edit", method: :patch %>

app/views/purchase_suppliers/index.html.erb
<% provide :index_title, "供应商管理界面" %>
<% provide :manage_object, PurchaseSupplier %>
<% provide :new_url, new_purchase_supplier_path %>

<h2 class="text-center"><%= yield(:index_title) %></h2>
<div class="row no-gutters">
  <% if can? :create, PurchaseSupplier %>
    <div class="create_order">
      <%= link_to "新建", yield(:new_url) %>
    </div>
  <% end %>
  <%= render 'shard/index_header', page: "purchase_supplier" %>
</div>
<table class="table table-hover table-active">
  <thead>
  <tr>
    <td>编号</td>
    <td>公司名</td>
    <td>联系号码</td>
  </tr>
  </thead>
  <tbody>
  <% @suppliers.each do |supplier| %>
    <tr>
      <td><%= supplier.id %></td>
      <td><%= link_to supplier.name, purchase_supplier_path(supplier) %></td>
      <td><%= supplier.phone %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= render 'shard/paginate', object: @suppliers %>

app/views/purchase_suppliers/new.html.erb
<% provide :button_text, "创建" %>
<% provide :title, "创建新的供应商" %>
<% provide :method, :post %>
<% provide :back_url, purchase_suppliers_path %>

<%= render 'shard/form', object: @supplier, url: purchase_suppliers_path, type: "purchase_supplier", type_2: "create"%>

app/views/purchase_suppliers/show.html.erb
<% provide :title, "供应商信息详情" %>
<% provide :edit_url, edit_purchase_supplier_path(@supplier) %>
<% provide :back_url, purchase_suppliers_path %>

<div class="text-center">
  <h2><%= yield(:title) %></h2>

  <%= render 'purchase_suppliers/show_content', object: @supplier %>

  <div>
    <% if can? :export, PurchaseSupplier %>
       <span data-hint="每个月要对账了，导出固定格式的全部记录，需要在Excel中把不必要的删除掉。" data-hintPosition="top-left">
         <%= link_to "导出对账单", export_purchase_supplier_path(@supplier, format: "xls"), class: "btn btn-primary export" %></span>
    <% end %>

    <% if can? :update, PurchaseSupplier %>
      <%= link_to "编辑", yield(:edit_url), class: "btn btn-primary edit-link" %>
    <% end %>
    <% if @supplier.purchase_orders.blank? && @supplier.expenses.blank? %>
      <% if can? :destroy, PurchaseSupplier %>
        <% if @supplier.purchase_orders.size == 0 && @supplier.expenses.size == 0 %>
         <span data-hint="只有关联的订单数为零的才能删除，慎重！" data-hintPosition="top-left">
           <%= link_to "删除", purchase_supplier_path, method: :delete, class: "btn btn-primary destroy-link",data: {confirm: "确定删除吗？请慎重"} %></span>
        <% end %>
      <% end %>
    <% end %>
    <%= link_to "返回主页", yield(:back_url), class: "btn btn-primary" %>
  </div>
</div>