config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  post 'check_orders_money', to: 'dashboard#check_orders_money'
  post 'check_trade_top', to: 'dashboard#check_trade_top'
  post 'check_expense_ratio', to: 'dashboard#check_expense_ratio'
  post 'check_purchase_supplier', to: 'dashboard#check_purchase_supplier'
  post 'check_sale_customer', to: 'dashboard#check_sale_customer'
  post 'intro_clear', to: 'dashboard#intro_clear'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :settings, only: [:index, :update]
  resources :outputs do
    collection do
      post :delete_list
    end
  end
  resources :introjs, only: [:create, :destroy] do
    collection do
      post :find_attribute
    end
  end
  resources :comments, only: [:index, :create, :destroy] do
    get :take_top, on: :member
  end
  resources :users do
    member do
      get :lock
      get :reset
    end
  end
  resources :employee
  resources :roles
  resources :purchase_suppliers do
    collection do
      get :check_purchase_supplier
    end
    member do
      get :export
    end
  end
  resources :sale_customers do
    collection do
      get :check_sale_customer
    end
    member do
      get :export
    end
  end
  resources :purchase_orders do
    member do
      get :pass_check
    end
  end
  resources :sale_orders do
    member do
      get :pass_check
    end
  end
  resources :materials do
    collection do
      get :check_material_name
      get :check_material_specification
    end
  end
  resources :products do
    collection do
      post :get_options
    end
  end
  resources :repos
  resources :proceeds do
    member do
      get :pass_check
    end
  end
  resources :expenses do
    member do
      get :pass_check
      get :pass_reimburse
    end
    collection do
      get :get_expense_type
    end
  end
  resources :change_machines do
    member do
      get :pass_settle
    end
  end
  resources :password_resets, :only => [:edit, :update]


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :purchase_supplier
  has_many :purchase_orders

  accepts_nested_attributes_for :purchase_supplier
  attr_accessor :purchase_supplier_attributes

  validates :name, presence: true, uniqueness: {scope: [:specification, :purchase_supplier_id]}
  validates :name, :specification, presence: true

  def self.search(search)
    if search
      where(" purchase_suppliers.name LIKE :term or materials.name LIKE :term or materials.specification LIKE :term  ", term: "%#{search}%")
    else
      all
    end
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :get_material, only: [:edit, :show, :update, :destroy]
  load_and_authorize_resource

  def index
    if params.has_key?(:search) && params[:search] != ""
      @materials = Material.joins(:purchase_suppliers).search(params[:search]).order("updated_at DESC").page(params[:page])
    else
      @materials = Material.order("updated_at DESC").page(params[:page])
    end
  end

  def new
    @material = Material.new
    @material.build_purchase_supplier
  end

  def show
    if @material.purchase_orders
      orders = @material.purchase_orders.select(:bill_time, :price).where(is_invalid: false, check_status: true)
      @bill_times = orders.map(&:bill_time)
      @prices = orders.map(&:price)
    end
  end

  def edit
    if @material.purchase_supplier.present?
      @purchase_supplier = @material.purchase_supplier
    else
      @material.build_purchase_supplier
    end
  end

  def create
    @material = Material.new(material_params)
    if !purchase_supplier = PurchaseSupplier.find_by(name: params[:material][:purchase_suppliers][:name])
      flash[:warning] = "供应商的名字不存在"
      @material.build_purchase_supplier
      render "materials/new"
    else
      @material.purchase_supplier = purchase_supplier
      if @material.save
        flash[:success] = "创建成功"
        redirect_to materials_url
      else
        flash[:warning] = "#{@material.errors.full_messages.join(',')}"
        @material.build_purchase_supplier
        render "materials/new"
      end
    end
  end


  def update
    if !purchase_supplier = PurchaseSupplier.find_by(name: params[:material][:purchase_suppliers][:name])
      flash[:warning] = "供应商的名字不存在"
      @material.build_purchase_supplier
      render "materials/new"
    else
      @material.purchase_supplier = purchase_supplier
      if @material.update(material_params)
        flash[:success] = "成功更新原材料信息"
        redirect_to material_url(@material)
      else
        flash[:warning] = "#{@material.errors.full_messages.join(',')}"
        @material.build_purchase_supplier
        render "materials/edit"
      end
    end
  end

  def destroy
    Material.delete(@material)
    redirect_to materials_path
  end

  def check_material_name
    @material_names = Material.search_name(params[:term]).map(&:name)
    render json: @material_names
  end

  def check_material_specification
    @material_specifications = Material.search_specification(params[:term]).map(&:specification)
    render json: @material_specifications
  end


  private

  def get_material
    @material = Material.find(params[:id])
  end

  def material_params
    params.require(:material).permit(:name, :description, :type, :specification, :batch_number, :measuring_unit, :tax_rate,
                                     :preset_price, :remarks, :status, :picture, :purchase_supplier_attributes => [:id, :name])
  end

end

app/helpers/material_helper.rb
module MaterialHelper
end

app/views/materials/_form_content.html.erb
<div class="form-group">
  <%= f.label :name, "品名" %>
  <%= f.text_field :name, required: "required", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :specification, "型号规格" %>
  <%= f.text_field :specification, required: "required", class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :measuring_unit, "计量单位" %>
  <%= f.select :measuring_unit, options_for_select([['包', '包'], ['件', '件'], ['箱', '箱']]), class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :preset_price, "预设价格(元)" %>
  <a class="fas fa-question-circle" data-toggle="tooltip" data-placement="right" title="预估设定的进价"> </a>
  <%= f.number_field :preset_price, step: 0.01, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.fields_for :purchase_suppliers do |ff| %>
    <%= ff.label :name, "公司名" %>
    <%= ff.text_field :name, required: "required", class: "form-control" %>
  <% end %>
</div>
<div class="form-group">
  <%= f.label :description, "描述" %>
  <%= f.text_field :description, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :remarks, "备注" %>
  <%= f.text_field :remarks, class: "form-control" %>
</div>

app/views/materials/_show_content.html.erb
<table class="table">
  <tbody>
  <tr>
    <th>品名</th>
    <td><%= object.name %></td>
  </tr>
  <tr>
    <th>型号规格</th>
    <td><%= object.specification %></td>
  </tr>

  <tr>
    <th>描述</th>
    <td><%= object.description %></td>
  </tr>
  <tr>
    <th>供应商</th>
    <td><%= object.purchase_supplier.name %></td>
  </tr>
  <tr>
    <th>计量单位</th>
    <td><%= object.measuring_unit %></td>
  </tr>
  <tr>
    <th>创建时间</th>
    <td><%= str_time object.created_at.localtime %></td>
  </tr>
  </tbody>
</table>

<% if @prices.uniq.size > 1 %>
  <h4>历史价格曲线</h4>
  <div class="chart-container">
    <canvas id="historical_price_chart">
    </canvas>
  </div>
<% end %>
<% if @prices.size > 0 %>
  <div class="purchase_orders_content">
    <div id="accordion">
      <div class="card">
        <div class="card-header">
          <a class="card-link" data-toggle="collapse" href="#collapse_1">
            <span>历史订单列表</span>
          </a>
        </div>
        <div id="collapse_1" class="collapse" data-parent="#accordion">
          <div class="card-body">
            <% @material.purchase_orders.each do |purchase_orders| %>
              <div>
                <%= link_to(purchase_orders.order_id, purchase_order_path(purchase_orders)) %> --
                <%= purchase_orders.price %>元/千克
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
    $(function () {
            if (<%=@prices.uniq.size>1 %>) {
                var ctx = $('#historical_price_chart');
                var myChart = new Chart(ctx, {
                    type: "line",
                    data: {
                        labels: <%= raw @bill_times.map{|n|str_date(n)}  %>,
                        datasets: [
                            {
                                label: '历史价格',
                                data: <%= raw @prices %>,
                                borderColor: "blue",
                                fill: false
                            }
                        ]
                    },
                    options: {
                        hover: {
                            animationDuration: 0  // 防止鼠标移上去，数字闪烁
                        },
                        animation: {           // 这部分是数值显示的功能实现
                            onComplete: function () {
                                var chartInstance = this.chart,

                                    ctx = chartInstance.ctx;
                                // 以下属于canvas的属性（font、fillStyle、textAlign...）
                                ctx.font = Chart.helpers.fontString(Chart.defaults.global.defaultFontSize, Chart.defaults.global.defaultFontStyle, Chart.defaults.global.defaultFontFamily);
                                ctx.fillStyle = "black";
                                ctx.textAlign = 'center';
                                ctx.textBaseline = 'bottom';

                                this.data.datasets.forEach(function (dataset, i) {
                                    var meta = chartInstance.controller.getDatasetMeta(i);
                                    meta.data.forEach(function (bar, index) {
                                        var data = dataset.data[index];
                                        ctx.fillText(data, bar._model.x, bar._model.y - 5);
                                    });
                                });
                            }
                        },

                        bezierCurve: true,
                        datasetStroke: true,
                        scales: {
                            yAxes: [{
                                ticks: {
                                    min: <%=@prices.min %>-1,
                                    max: <%=@prices.max %>+1
                                }
                            }]
                        }
                    }
                });
            }
        }
    )
</script>

app/views/materials/edit.html.erb
<% provide :button_text, "更新" %>
<% provide :title, "修改原料信息" %>
<% provide :method, :patch %>
<% provide :back_url, materials_path %>

<%= render 'shard/form', object: @material, url: material_path, type: "material", type_2: "edit" %>

app/views/materials/index.html.erb
<% provide :index_title, "原料管理界面" %>
<% provide :new_url, new_material_path %>

<h2 class="text-center"><%= yield(:index_title) %></h2>
<div class="row no-gutters">

  <% if can? :create, Material %>
    <div class="create_order">
      <%= link_to "新建", yield(:new_url) %>
    </div>
  <% end %>
  <%= render 'shard/index_header', page: "material" %>
</div>
<table class="table table-hover table-active">
  <thead>
  <tr>
    <td>品名</td>
    <td>型号</td>
    <td>供应商</td>
  </tr>
  </thead>
  <tbody>
  <% @materials.each do |material| %>
    <tr>
      <td><%= link_to material.name, material_path(material) %></td>
      <td><%= material.specification %></td>
      <td><%= link_to material.purchase_supplier.name, purchase_supplier_path(material.purchase_supplier.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render 'shard/paginate', object: @materials %>

app/views/materials/new.html.erb
<% provide :button_text, "创建" %>
<% provide :title, "创建新原料" %>
<% provide :method, :post %>
<% provide :back_url, materials_path %>

<%= render 'shard/form', object: @material, url: materials_path, type: "material", type_2: "create", method: :post %>

app/views/materials/show.html.erb
<% provide :title, "原材料详情" %>
<% provide :edit_url, edit_material_path(@material) %>
<% provide :back_url, materials_path %>


<div class="text-center">
  <h2><%= yield(:title) %></h2>
  <%= render 'materials/show_content', object: @material, type: "material" %>
  <div>
    <% if can? :update, Material %>
      <%= link_to "编辑", yield(:edit_url), class: "btn btn-primary edit-link" %>
    <% end %>
    <%= link_to "返回主页", yield(:back_url), class: "btn btn-primary" %>
  </div>
</div>