config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  post 'check_orders_money', to: 'dashboard#check_orders_money'
  post 'check_trade_top', to: 'dashboard#check_trade_top'
  post 'check_expense_ratio', to: 'dashboard#check_expense_ratio'
  post 'check_purchase_supplier', to: 'dashboard#check_purchase_supplier'
  post 'check_sale_customer', to: 'dashboard#check_sale_customer'
  post 'intro_clear', to: 'dashboard#intro_clear'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :settings, only: [:index, :update]
  resources :outputs do
    collection do
      post :delete_list
    end
  end
  resources :introjs, only: [:create, :destroy] do
    collection do
      post :find_attribute
    end
  end
  resources :comments, only: [:index, :create, :destroy] do
    get :take_top, on: :member
  end
  resources :users do
    member do
      get :lock
      get :reset
    end
  end
  resources :employee
  resources :roles
  resources :purchase_suppliers do
    collection do
      get :check_purchase_supplier
    end
    member do
      get :export
    end
  end
  resources :sale_customers do
    collection do
      get :check_sale_customer
    end
    member do
      get :export
    end
  end
  resources :purchase_orders do
    member do
      get :pass_check
    end
  end
  resources :sale_orders do
    member do
      get :pass_check
    end
  end
  resources :materials do
    collection do
      get :check_material_name
      get :check_material_specification
    end
  end
  resources :products do
    collection do
      post :get_options
    end
  end
  resources :repos
  resources :proceeds do
    member do
      get :pass_check
    end
  end
  resources :expenses do
    member do
      get :pass_check
      get :pass_reimburse
    end
    collection do
      get :get_expense_type
    end
  end
  resources :change_machines do
    member do
      get :pass_settle
    end
  end
  resources :password_resets, :only => [:edit, :update]


# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  load_and_authorize_resource

  def index
    if params.has_key?(:search) && params.has_key?(:type)
      type = params[:type].split(":")
      @expenses = Expense.left_outer_joins(:purchase_suppliers).search(params[:search]).where("#{type[0]}=?", type[1]).
          references(:purchase_suppliers).order(params[:order]).page(params[:page])
    elsif params.has_key?(:type) && params[:type] != ""
      type = params[:type].split(":")
      @expenses = Expense.left_outer_joins(:purchase_suppliers).where("#{type[0]}=?", type[1]).references(:purchase_suppliers).order("created_at DESC").page(params[:page])
    elsif params.has_key?(:search) && params[:search] != ""
      @expenses = Expense.left_outer_joins(:purchase_suppliers).search(params[:search]).references(:purchase_suppliers).order("created_at DESC").page(params[:page])
    else
      @expenses = Expense.order("created_at DESC").page(params[:page])
    end
  end

  def new
    @expense = Expense.new
  end

  def edit
    if !@expense.check_status
      @expense
    else
      flash[:warning] = "收款单已审核，不可更改"
      render "expenses/show"
    end
  end

  def show
    unless request.referrer =~ /(new|edit)/
      store_referrer_location
    end
  end

  def create
    @expense = Expense.new(expense_params)
    if @expense.save
      @expense.build_purchase_supplier
      flash[:success] = "创建成功"
      redirect_to expense_path(@expense)
    else
      flash[:warning] = "#{@expense.errors.full_messages.join(',')}"
      render "expenses/new"
    end
  end

  def update
    if !@expense.check_status
      if @expense.update(expense_params)
        @expense.build_purchase_supplier
        flash[:success] = "成功更新付款单信息"
        redirect_to expense_path(@expense.id)
      else
        flash[:warning] = "#{@expense.errors.full_messages.join(',')}"
        render "expenses/edit"
      end
    else
      flash[:warning] = "付款单已审核，不可更改"
      redirect_to expense_url(@expense.id)
    end
  end

  def destroy
    store_referrer_location
    if @expense.check_status
      @expense.order_declare_invalid(current_user)
      @expense.calcu_to_purchase_supplier if @expense.purchase_suppliers
      flash[:success] = "付款单#{@expense.order_id}已作废"
    else
      @expense.delete
      flash[:success] = "付款单#{@expense.order_id}已删除"
    end
    redirect_back_referrer_for expenses_path
  end

  def pass_check
    if !@expense.is_invalid
      @expense.pass_check_result(current_user)
      @expense.calcu_to_purchase_supplier if @expense.purchase_suppliers
      flash[:success] = "#{@expense.counterparty}的付款单已审核"
      if Setting.setting_status("连续审核") && next_order = Expense.find_by(check_status: false)
        redirect_to expense_path(next_order)
      else
        redirect_back_referrer_for(expenses_url)
      end
    else
      flash[:warning] = "已作废的无法通过审核"
      redirect_back_referrer_for(expenses_url)
    end
  end

  def pass_reimburse
    @expense.pass_reimburse_expense
    flash[:success] = "#{@expense.counterparty}的付款单已通过报销"
    redirect_back_referrer_for(expense_url(@expense.id))
  end

  def get_expense_type
    @expense = Expense.search_expense_type(params[:term]).map(&:expense_type).uniq
    render json: @expense
  end

  private

  def expense_params
    params.require(:expense).permit(:expense_type, :counterparty, :user_id, :paper_amount, :actual_amount, :remark,
                                    :account_number, :account_name, :account_from, :picture, :need_reimburse, :bill_time)
  end

end

app/views/expenses/_form_content.html.erb
<div class="form-group" data-step="1" data-intro="付款对象,可按空格搜索已经存在的供应商名称,可以填写别的名称">
  <%= f.label :counterparty, "交易方" %>
  <a class="fas fa-magic" data-toggle="tooltip" data-placement="right" title="已设定自动填充"> </a>
  <%= f.text_field :counterparty, class: "form-control", placeholder: "必须填写，对方名称", required: "required", data: {autocomplete_source: check_purchase_supplier_purchase_suppliers_path} %>
</div>
<div class="form-group" data-step="2" data-intro="付款的类型，可按空格查看已有的类型">
  <%= f.label :expense_type, "类型" %>
  <a class="fas fa-magic" data-toggle="tooltip" data-placement="right" title="已设定自动填充，按空格试一下"> </a>
  <%= f.text_field :expense_type, class: "form-control", placeholder: "必须填写，该笔付款的类型", required: "required", data: {autocomplete_source: get_expense_type_expenses_path} %>
</div>
<div class="form-group" data-step="3" data-intro="账面上的付款金额，有时候一些零头会舍去，但这里要填写账目上完整的金额">
  <%= f.label :paper_amount, "账面金额" %>
  <%= f.number_field :paper_amount, placeholder: 0, min: 0, required: "required", step: 0.01, class: "form-control" %>
</div>
<div class="form-group" data-step="4" data-intro="与账面金额对应，这里填写实际的付款金额，舍去的零头就不用记录了">
  <%= f.label :actual_amount, "实际金额" %>
  <%= f.number_field :actual_amount, placeholder: 0, min: 0, required: "required", step: 0.01, class: "form-control" %>
</div>
<div class="form-group" data-step="5" data-intro="转账的话，就是对方的账户名">
  <%= f.label :account_name, "户名" %>
  <%= f.text_field :account_name, placeholder: "非必须", class: "form-control" %>
</div>
<div class="form-group" data-step="6" data-intro="与上方对应，银行卡号或者支付宝、微信号">
  <%= f.label :account_number, "账户号码" %>
  <%= f.text_field :account_number, placeholder: "非必须", class: "form-control" %>
</div>
<div class="form-group" data-step="7" data-intro="选择一下账户来往的类型">
  <%= f.label :account_from, "账户所属" %>
  <%= f.select :account_from, options_for_select([['银行', '银行'], ['支付宝', '支付宝'], ['微信', '微信'], ['其他', '其他']]), class: "form-control" %>
</div>
<div class="form-group" data-step="8" data-intro="这个账单的时间，如果是补以前的账单，记得这里要改成账单上的时间，默认是现在的时间">
  <%= f.label :bill_time, "账单时间" %>
  <a class="far fa-question-circle" data-toggle="tooltip" data-placement="right" title="该笔付款的时间记录"> </a>
  <%= f.datetime_field :bill_time, value: default_time_now, class: "form-control" %>
</div>
<% if type_2 == "edit" %>
  <div class="form-group">
    <%= f.label :user_id, "经手人" %>
    <%= f.select(:user_id, options_for_select(User.all.map {|n| [n.name, n.id]}, object.user_id), class: "form-control") %>
  </div>
<% elsif type_2 == "create" %>
  <div class="form-group d-none">
    <%= f.label :user_id, "经手人ID" %>
    <%= f.number_field(:user_id, value: current_user.id, class: "form-control") %>
  </div>
<% end %>
<div class="form-group" data-step="9" data-intro="账单填写人是否代公司先出了这笔费用，勾上后，该账单将会记入报销流程">
  <%= f.label :need_reimburse, "需要报销？" %>
  <a class="far fa-question-circle" data-toggle="tooltip" data-placement="right" title="账单填写人是否代公司先出了这笔费用？"> </a>
  <%= f.check_box :need_reimburse %>
</div>
<div class="picture" data-step="10" data-intro="付款单之类的凭证，可以拍照上传保留">
  <%= label_tag "上传相关图片" %>
  <%= f.file_field :picture %>
</div>

app/views/expenses/_show_content.html.erb
<table class="table">
  <tbody>

  <tr>
    <th>交易方</th>
    <td><%= object.counterparty %></td>
  </tr>
  <% if object.purchase_suppliers.any? %>
    <tr>
      <th>关联地址</th>
      <td><%= link_to object.purchase_suppliers[0].name, purchase_supplier_path(object.purchase_suppliers[0]) %></td>
    </tr>
  <% end %>
  <tr>
    <th>账面金额</th>
    <td><%= object.paper_amount %>元</td>
  </tr>

  <tr>
    <th>实际金额</th>
    <td><%= object.actual_amount %>元</td>
  </tr>

  <tr>
    <th>备注</th>
    <td><%= object.remark %></td>
  </tr>
  <tr>
    <th>账户名称</th>
    <td><%= object.account_name %></td>
  </tr>
  <tr>
    <th>账户号码</th>
    <td><%= object.account_number %></td>
  </tr>
  <tr>
    <th>账户类型</th>
    <td><%= object.account_from %></td>
  </tr>
  <tr>
    <th>经手人</th>
    <td><%= object.user.name %></td>
  </tr>

  <tr>
    <th>付款时间</th>
    <td><%= str_time(object.bill_time) %></td>
  </tr>


  <% if object.create_person != object.user.name %>
    <tr>
      <th>创建者</th>
      <td><%= object.create_person %></td>
    </tr>
  <% end %>
  <% if object.check_status %>
    <tr>
      <th>审核人</th>
      <td> <%= object.check_person %></td>
    </tr>
    <tr>
      <th>审核时间</th>
      <td> <%= str_time(object.check_time) %></td>
    </tr>
  <% end %>
  <% if object.need_reimburse %>
    <tr>
      <th class="alert-danger">需要报销</th>
      <td class="alert-danger"> <%= object.user.name %></td>
    </tr>
  <% end %>
  <% if object.reimbursed %>
    <tr>
      <td colspan="2" class="alert-success">已报销</td>
    </tr>
  <% end %>
  <tr>
    <td colspan="2"><%= image_tag object.picture.url, size: "125x160" if object.picture? %></td>
  </tr>
  </tbody>
</table>

app/views/expenses/edit.html.erb
<% provide :button_text, "更新" %>
<% provide :title, "修改付款单" %>
<% provide :method, :patch %>
<% provide :back_url, expenses_path %>

<%= render 'shard/form', object: @expense, url: expense_path, type: "expense", type_2: "edit" %>

app/views/expenses/index.html.erb
<% provide :index_title, "付款单界面" %>
<% provide :new_url, new_expense_path %>

<h2 class="text-center"><%= yield(:index_title) %></h2>
<div class="row no-gutters">

  <% if can? :create, Expense %>
    <div class="create_order">
      <%= link_to "新建", yield(:new_url) %>
    </div>
  <% end %>
  <%= render 'shard/index_header', page: "expense" %>

</div>

<% if @expenses.blank? %>
  <div class="alert-info text-center">空空如也</div>
<% else %>
  <% @expenses.each do |expense| %>
    <div class="expense_info <%= check_status_css(expense) %>">
      <div class="content">
        <div class="row no-gutters">
          <div class="expense_date">单号:<%= link_to expense.order_id, expense_path(expense) %></div>
          <p class=" ml-auto">
            <% if expense.need_reimburse %>
            <div class="need_reimburse">未报销|</div>
          <% end %>
          <div class="check_status "><%= expense.expense_type %></div>
          </p>
        </div>
        <div class="row no-gutters">
          <div class="expense_supplier">交易方:<%= expense.counterparty %></div>
          <div class="check_status ml-auto">
            <% if !expense.check_status %>
              未审核
            <% end %>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="expense_remark col-auto">备注:<%= expense.remark %></div>
          <% if can? :destroy, Expense %>
            <div class="operation_right ml-auto">
              <% if expense.is_invalid %>
                <%= expense.declare_invalid_person %>已将其作废
              <% elsif !expense.check_status %>
                <%= link_to "删除", expense_path(expense), method: :delete, data: {confirm: "未审核的单据会被直接删除，确定吗？"}, class: " destroy_link" %></span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<%= render 'shard/paginate', object: @expenses %>

app/views/expenses/new.html.erb
<% provide :button_text, "创建" %>
<% provide :title, "创建付款单" %>
<% provide :method, :post %>
<% provide :back_url, expenses_path %>

<%= render 'shard/form', object: @expense, url: expenses_path, type: "expense", type_2: "create" %>

app/views/expenses/show.html.erb
<% provide :title, "付款单详情" %>


<div class="text-center">
  <h2><%= yield(:title) %>
    <%if @expense.is_invalid? %>
      <span class="is_invalid_alert">已作废</span>
    <%end %>
  </h2>
  <%= render 'expenses/show_content', object: @expense, type: "expense" %>
  <div>
    <% if !@expense.is_invalid && !@expense.check_status %>
      <% if can? :pass_check, Expense %>
        <div class="alert-warning"><%= param_check("连续审核") %></div>
        <span data-hint="您具有审核的权限,请确认单据内容正确后点击此按钮后，单据将记入系统计算。注意:已审核的单据无法编辑修改，如有错误只能作废后重新填写一张！" data-hintPosition="top-left">
          <%= link_to "通过审核", pass_check_expense_path(@expense), class: "btn btn-primary pass_check_link" %></span>
      <% end %>
      <% if can? :update, Expense %>
       <span data-hint="单子上有内容错误？缺失？重新编辑吧！注意:作废的单据和通过审核的单据就无法修改了！" data-hintPosition="top-left">
         <%= link_to "编辑", edit_expense_path(@expense), class: "btn btn-primary edit_link" %></span>
      <% end %>
    <% end %>

    <% if !@expense.is_invalid && @expense.check_status %>
      <% if can? :destroy, Expense %>
          <span data-hint="单据错误？审核后不能修改了，只能作废后再写一张了。" data-hintPosition="top-left">
            <%= link_to "作废", expense_path(@expense), method: :delete, data: {confirm: "确定作废吗？"}, class: "btn btn-primary destroy_link" %></span>
      <% end %>
    <% end %>

    <% if @expense.need_reimburse && @expense.check_status && !@expense.is_invalid %>
      <% if can? :pass_check, Expense %>
          <span data-hint="您具有通过报销此单据的权限，在付给报销人报销款后，请点击此按钮，报销结果将在报销人的个人界面显示。" data-hintPosition="top-left">
            <%= link_to "已报销", pass_reimburse_expense_path(@expense), class: "btn btn-primary" %></span>
      <% end %>
    <% end %>
    <%= link_to "返回主页", expenses_path, class: "btn btn-primary" %>
  </div>
</div>